### ISSUE TITLE
Import order (is pep8 linting working?)

### ISSUE THREAD

**Issue by ssangervasi** [ilyakatz/dividend_chaser#14]
https://www.python.org/dev/peps/pep-0008/#imports

> Imports should be grouped in the following order:
> 
>     Standard library imports.
>     Related third party imports.
>     Local application/library specific imports.
> 
> You should put a blank line between each group of imports.

**Comment by ilyakatz** [comment]
Looks like pep8 does not actually check for this (https://github.com/hhatto/autopep8/issues/144) but pylint does. So i'm going to configure pylint in addition to pep8
