### ISSUE TITLE
File are opened but not closed

### ISSUE THREAD

**Issue by ssangervasi** [ilyakatz/dividend_chaser#15]
[Example](https://github.com/ilyakatz/dividend_chaser/blob/master/dividend_chaser/workers/dividend_history.py#L31)

```py
@classmethod
  def loadStocks(self):
    file = open(DividendHistory.filename)
    obj = json.load(file)
    return obj
```

[Docs](https://docs.python.org/3/tutorial/inputoutput.html?highlight=file#reading-and-writing-files)

> It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point. Using with is also much shorter than writing equivalent try-finally blocks:

**Comment by ilyakatz** [comment]
Oh, that's what it was. I saw `with` before but couldn't understand what that did
