### ISSUE TITLE
Virtualenv installation should be gitignored

### ISSUE THREAD

**Issue by ssangervasi** [ilyakatz/dividend_chaser#6]
It looks like you initialized the virtualenv inside the repo root directory and committed it. The contents of the venv are specific to the machine that installed the packages, so they are not useful if you clone the repo on a different machine (CI environment, etc.). For example, [here is a symlink to the particular installation of Py3.7 on your machine](https://github.com/ilyakatz/dividend_chaser/blob/master/dividends_chaser/include/python3.7m).

The more common use of of virutalenv is to stick each one under `~/.venvs/{project_name}`, which a little like to how Ruby sticks packages in in `~/.gem`.

Alternatively, you can take the `node_modules` approach and stick it under the repo root, but make sure you git ignore it and _don't give it the same name as the project_ because that might cause weird python import mistakes.

**Comment by ilyakatz** [comment]
oh, cool, that's a good one 🙇

**Comment by ilyakatz** [comment]
Fixed via #10
